### PR TITLE
Added README, token generation, error handler, routes for all required use cases

### PR DESCRIPTION
**Pull request by PaulaSazonov**
Added README, routes now handling all required use cases, added token-generating and error handler

### CODE REVIEW

**Comment by srd90** [comment]
About these:
> https://github.com/PaulaSazonov/suomifi/pull/1/commits/842a0832538916f017fc026ee51da30cc9489429#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R44
> ... The latter case is to terminate the authentication session within suomi.fi, if a logout is initiated by an another SP. The authentication session within suomi.fi is valid for 32 minutes, during that time you could authenticate to multiple services that use suomi.fi (Vero, Kela, etc.), and this just means that if the authentication session is terminated in one service, it is terminated in all of them.

and 

> https://github.com/PaulaSazonov/suomifi/pull/1/commits/842a0832538916f017fc026ee51da30cc9489429#diff-336525865815cfe527e7b7352690bb5ad65c119c04c0023919ca9ae9878e2af3R104
> https://github.com/PaulaSazonov/suomifi/blob/842a0832538916f017fc026ee51da30cc9489429/src/routes/router.ts#L101-L114

This reference implementation's IdP initiated Logout handling (i.e. case "2: IdP request logout after receive logout request from another SP that shared a session. ") doesn't work properly at all circumstances and whats worse it reports success even if it fails to terminate local session (as matter of fact it reports always success regardless of success/failure of local session termination).
This means that user's local session to service which uses this reference implementation might not be terminated even though it was reported to user that all sessions started during SSO were terminated successfully.
Next person who starts to use browser (in schools, libraries, any shared computers, etc.) and writes to address bar a service which uses this reference implementation might see previous user's information if local session has not timed out. Local session's timeout might be significantly longer than IdP's SSO session TTL and local session's TTL is not bound to SSO session's TTL (even if it would be there would still be 0-32min to "reuse" previous user's local session).

Further information available from:
1. https://github.com/node-saml/passport-saml/issues/221#issuecomment-1048200363
    * on of the comments of aforementioned issue  
3. https://github.com/node-saml/passport-saml/issues/419

There are two publicly available implementations which try to handle situation correctly  but those implementations are very application specific (as of now it is impossible to implement IdP initiated SLO properly with [passport-saml](https://github.com/node-saml/passport-saml) or with [node-saml](https://github.com/node-saml/node-saml) so that one implementation would work in all SW stacks / applications). Those publicly available implementations which **might** implement it correctly (and which **might** be used as example how to address IdP initated SLO problem) are:
* https://github.com/espoon-voltti/evaka/pull/738
   * see aforementioned PR's summary
   * license might be LGPL
* https://github.com/node-saml/passport-saml/issues/221#issuecomment-1285753685
  * an another comment from that issue

fwiw this problem was discussed previously at your this issue report: https://github.com/node-saml/passport-saml/issues/445

**Comment by PaulaSazonov** [comment]
Thank you @srd90 for the input! That was a very good point, I added a logout handler to terminate the local session as well.

**Comment by srd90** [comment]
I am sorry to inform you that https://github.com/PaulaSazonov/suomifi/pull/1/commits/7372ab87a7d9b9f81207896b0435ead93a463679 did not address or fix issue described at previous comment at all.

Please, take a good look at all the material linked to this PR's previous comment.

Hint: issue is related to the fact that 3rd party (session) cookies are not being delivered in modern browser under all circumstances (e.g. when IdP which lives another top level domain is propagating SLO requests from iframes). When there is not any session cookie available there cannot be any authenticated `reg.session` associated by underlying session management subsystem to be destroyed and certainly not the authenticated session which was designated by information in IdP initiated logoutrequest SAML XML message ( ... some SW stacks might have been configured to create new local session implicitly if there aren't any due lack of session cookie etc etc but that is another session).

Under such conditions (not being 100% sure that correct local session was terminated) SAML service provider must not report successfull local session termination. If SAML service provided is not 100% sure it must report with some other response code.

This was last attempt to comment this particular codebase.

**Comment by PaulaSazonov** [comment]
Yes, I understand your point. This codebase was to serve as a reference to myself, and it is not a full implementation (the proper cache for the sessions is not implemented at all). I will try to build on this if I have the time, but for now it is more of a hobby project.

**Pull request merged**
